#!/usr/bin/python3
import os

PROJECT_ROOT = '.'
UPLOAD_FOLDER = os.path.join(PROJECT_ROOT, 'uploads/')
CONNECTIVITY_FOLDER = os.path.join(PROJECT_ROOT, 'connectivity')
SCHEMA_FILE = 'schema.sql'
DATABASE_FILE = 'database.db'
DATABASE_SCHEMA = os.path.join(CONNECTIVITY_FOLDER, SCHEMA_FILE)
DATABASE = os.path.join(CONNECTIVITY_FOLDER, DATABASE_FILE)

DATABASE_SCHEMA_FILE = DATABASE_SCHEMA


AUCTION_REQUESTS_LIST_APPROVED = 1
AUCTION_REQUESTS_LIST_NOT_APPREVED = 0
AUCTION_REQUESTS_LIST_BOTH = 2

MESSAGE_KEY_TO = 'msg_to'
MESSAGE_KEY_FROM = 'msg_from'

USER_ROLE_ADMIN = 'admin'
USER_ROLE_MANAGER = 'manager'
USER_ROLE_USER = 'user'

ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'admin'


